// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Tue Dec 06 14:16:10 2022

calc_out calc_out_inst
(
	.A(A_sig) ,	// input [7:0] A_sig
	.LoadOU(LoadOU_sig) ,	// input  LoadOU_sig
	.clock(clock_sig) ,	// input  clock_sig
	.a1(a1_sig) ,	// output  a1_sig
	.b1(b1_sig) ,	// output  b1_sig
	.c1(c1_sig) ,	// output  c1_sig
	.d1(d1_sig) ,	// output  d1_sig
	.e1(e1_sig) ,	// output  e1_sig
	.f1(f1_sig) ,	// output  f1_sig
	.g1(g1_sig) ,	// output  g1_sig
	.a2(a2_sig) ,	// output  a2_sig
	.b2(b2_sig) ,	// output  b2_sig
	.c2(c2_sig) ,	// output  c2_sig
	.d2(d2_sig) ,	// output  d2_sig
	.e2(e2_sig) ,	// output  e2_sig
	.f2(f2_sig) ,	// output  f2_sig
	.g2(g2_sig) ,	// output  g2_sig
	.a3(a3_sig) ,	// output  a3_sig
	.b3(b3_sig) ,	// output  b3_sig
	.c3(c3_sig) ,	// output  c3_sig
	.d3(d3_sig) ,	// output  d3_sig
	.e3(e3_sig) ,	// output  e3_sig
	.f3(f3_sig) ,	// output  f3_sig
	.g3(g3_sig) ,	// output  g3_sig
	.a4(a4_sig) ,	// output  a4_sig
	.b4(b4_sig) ,	// output  b4_sig
	.c4(c4_sig) ,	// output  c4_sig
	.d4(d4_sig) ,	// output  d4_sig
	.e4(e4_sig) ,	// output  e4_sig
	.f4(f4_sig) ,	// output  f4_sig
	.g4(g4_sig) 	// output  g4_sig
);

