// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Tue Dec 06 15:00:44 2022

control_unit control_unit_inst
(
	.clock(clock_sig) ,	// input  clock_sig
	.reset(reset_sig) ,	// input  reset_sig
	.in(in_sig) ,	// input  in_sig
	.out(out_sig) ,	// output  out_sig
	.LoadOU(LoadOU_sig) ,	// output  LoadOU_sig
	.Iuau(Iuau_sig) ,	// output  Iuau_sig
	.LoadA(LoadA_sig) ,	// output  LoadA_sig
	.LoadB(LoadB_sig) ,	// output  LoadB_sig
	.LoadR(LoadR_sig) ,	// output  LoadR_sig
	.clear(clear_sig) 	// output  clear_sig
);

defparam control_unit_inst.s0 = 'b00;
defparam control_unit_inst.s1 = 'b01;
defparam control_unit_inst.s2 = 'b10;
defparam control_unit_inst.s3 = 'b11;
