// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Tue Dec 06 14:14:23 2022

two_funct_au two_funct_au_inst
(
	.A(A_sig) ,	// input [7:0] A_sig
	.Cin(Cin_sig) ,	// input  Cin_sig
	.reset(reset_sig) ,	// input  reset_sig
	.LoadA(LoadA_sig) ,	// input  LoadA_sig
	.LoadB(LoadB_sig) ,	// input  LoadB_sig
	.LoadR(LoadR_sig) ,	// input  LoadR_sig
	.Cout(Cout_sig) ,	// output  Cout_sig
	.out_reg(out_reg_sig) 	// output [7:0] out_reg_sig
);

